monitor_on:
  name: Turn on monitor
  description: Turn on monitor for Magic Mirror

monitor_off:
  name: Turn off monitor
  description: Turn off monitor for Magic Mirror

monitor_toggle:
  name: Toggle monitor
  description: Toggle monitor for Magic Mirror

shutdown:
  name: Shutdown
  description: Shutdown Magic Mirror

reboot:
  name: Reboot
  description: Reboot Magic Mirror

restart:
  name: Restart
  description: Restart Magic Mirror

minimize:
  name: Minimize
  description: Minimize Magic Mirror

toggle_fullscreen:
  name: Toggle fullscreen
  description: Toggle fullscreen Magic Mirror

devtools:
  name: Devtools
  description: Devtools Magic Mirror

refresh:
  name: refresh
  description: refresh Magic Mirror

brightness:
  name: brightness
  description: brightness Magic Mirror
  fields:
    brightness:
      name: Brightness
      description: Brightness
      example: 100
      required: true
      selector:
        number:
          min: 0
          max: 100

module:
  name: module
  description: module Magic Mirror

module_action:
  name: module_action
  description: module_action Magic Mirror

module_installed:
  name: module_installed
  description: module_installed Magic Mirror

module_available:
  name: module_available
  description: module_available Magic Mirror

module_update:
  name: module_update
  description: module_update Magic Mirror

module_install:
  name: module_install
  description: module_install Magic Mirror

notification:
  name: notification
  description: notification Magic Mirror
  fields:
    title:
      name: title
      description: title
      example: title
      required: true
      selector:
        text:
    message:
      name: message
      description: message
      example: message
      required: true
      selector:
        text:
    timer:
      name: timer
      description: timer
      example: timer
      required: true
      selector:
        number:
          min: 1000
          max: 10000

alert:
  name: alert
  description: alert Magic Mirror
  fields:
    title:
      name: title
      description: title
      example: title
      required: true
      selector:
        text:
    message:
      name: message
      description: message
      example: message
      required: true
      selector:
        text:
    timer:
      name: Timer
      description: Timer
      example: Timer
      required: true
      selector:
        number:
          min: 1000
          max: 10000
