notification:
  name: notification
  description: notification Magic Mirror
  fields:
    title:
      name: title
      description: title
      example: title
      required: true
      selector:
        text:
    message:
      name: message
      description: message
      example: message
      required: true
      selector:
        text:
    timer:
      name: timer
      description: timer
      example: timer
      required: true
      selector:
        number:
          min: 1000
          max: 10000

alert:
  name: alert
  description: alert Magic Mirror
  fields:
    title:
      name: title
      description: title
      example: title
      required: true
      selector:
        text:
    message:
      name: message
      description: message
      example: message
      required: true
      selector:
        text:
    timer:
      name: Timer
      description: Timer
      example: Timer
      required: true
      selector:
        number:
          min: 1000
          max: 10000
