monitor_on:
  name: Turn on monitor
  description: Turn on monitor for Magic Mirror

monitor_off:
  name: Turn off monitor
  description: Turn off monitor for Magic Mirror

monitor_toggle:
  name: Toggle monitor
  description: Toggle monitor for Magic Mirror

brightness:
  name: brightness
  description: brightness Magic Mirror
  fields:
    brightness:
      name: Brightness
      description: Brightness
      example: 100
      required: true
      selector:
        number:
          min: 0
          max: 100

notification:
  name: notification
  description: notification Magic Mirror
  fields:
    title:
      name: title
      description: title
      example: title
      required: true
      selector:
        text:
    message:
      name: message
      description: message
      example: message
      required: true
      selector:
        text:
    timer:
      name: timer
      description: timer
      example: timer
      required: true
      selector:
        number:
          min: 1000
          max: 10000

alert:
  name: alert
  description: alert Magic Mirror
  fields:
    title:
      name: title
      description: title
      example: title
      required: true
      selector:
        text:
    message:
      name: message
      description: message
      example: message
      required: true
      selector:
        text:
    timer:
      name: Timer
      description: Timer
      example: Timer
      required: true
      selector:
        number:
          min: 1000
          max: 10000
